services:
  db:
    container_name: prisma_postgres
    restart: always
    image: postgres:12
    environment:
      POSTGRES_USER: ${DEV_USERNAME}
      POSTGRES_PASSWORD: ${DEV_PASSWORD}
      POSTGRES_DB: ${DEV_DATABASE}
    ports:
      - '${DEV_PORT}:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}
